spring.application.name=mercora-api

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true


management.endpoints.web.exposure.include=health,info,metrics

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html